name: Deploy to Azure DevOps

on:
  [push, pull_request]
  
jobs:
  deploy:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Actions
      uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: https://dev.azure.com/clouduserpb3cc6bef/MyFirstProject
        azure-pipeline-name: githrajesh-actions
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
       
        
